name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci || npm install
        else
          echo "No package.json found, creating basic one..."
          npm init -y
        fi
        
    - name: Basic validation
      run: |
        echo "🔍 Validating project structure..."
        
        # Check essential files
        FILES_OK=true
        
        if [ ! -f "index.html" ]; then
          echo "❌ index.html not found"
          FILES_OK=false
        else
          echo "✅ index.html found"
        fi
        
        if [ ! -f "style.css" ]; then
          echo "❌ style.css not found"
          FILES_OK=false
        else
          echo "✅ style.css found"
        fi
        
        if [ ! -f "contact-sharer.js" ]; then
          echo "❌ contact-sharer.js not found"
          FILES_OK=false
        else
          echo "✅ contact-sharer.js found"
        fi
        
        if [ "$FILES_OK" = false ]; then
          echo "❌ Some essential files are missing"
          exit 1
        fi
        
        echo "✅ All essential files found"
        
    - name: Deploy to Vercel (Preview)
      if: github.event_name == 'pull_request' && contains(github.event.head_commit.message, '[deploy]')
      run: |
        if [ ! -z "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "Deploying to Vercel preview..."
          npx vercel --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        else
          echo "⚠️ Vercel token not configured, skipping deployment"
        fi
        
    - name: Deploy to Vercel (Production)
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && contains(github.event.head_commit.message, '[deploy]')
      run: |
        if [ ! -z "${{ secrets.VERCEL_TOKEN }}" ]; then
          echo "Deploying to Vercel production..."
          npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
        else
          echo "⚠️ Vercel token not configured, skipping deployment"
        fi
        
    - name: Success message
      run: |
        echo "🎉 Workflow completed successfully!"
        echo "Project structure validated ✅"
        echo "Ready for deployment 🚀"